name: Go

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:

  validate:
    name: validate
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      working-directory: ${{ matrix.project }}
      run: go test -v -coverprofile=coverage.out
    
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build
      working-directory: ${{ matrix.project }}
      run: go build -v .