name: Go

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:

  validate:
    name: validate
    runs-on: ubuntu-20.04

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: List
      run: ls -lah

    - name: Test
      run: go test -v -coverprofile=coverage.out
    
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build
      run: go build -v .